[project]
name = 'bitflow'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.alt-sip-010-trait-ft-standard]
path = 'contracts/alt-sip-010-trait-ft-standard.clar'
clarity_version = 1
epoch = 2.05

[contracts.lp-trait]
path = 'contracts/lp-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.1

[contracts.stableswap]
path = 'contracts/stableswap.clar'
clarity_version = 2
epoch = 2.1

[contracts.stableswap-fee-escrow]
path = 'contracts/stableswap-fee-escrow.clar'
clarity_version = 2
epoch = 2.1

[contracts.stableswap-staking-and-rewards]
path = 'contracts/stableswap-staking-and-rewards.clar'
clarity_version = 2
epoch = 2.1

[contracts.susdt-token]
path = 'contracts/susdt-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.usda-susdt-lp-token]
path = 'contracts/usda-susdt-lp-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.usda-token]
path = 'contracts/usda-token.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
