[project]
name = 'bitflow'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.staking-and-rewards-stackingDAO]
path = 'contracts/staking-and-rewards-stackingDAO.clar'
clarity_version = 2
epoch = 2.1

[contracts.lp-trait]
path = 'contracts/lp-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.1

[contracts.stableswap]
path = 'contracts/stableswap.clar'
clarity_version = 2
epoch = 2.1

[contracts.stableswap-stackingDAO]
path = 'contracts/stableswap-stackingDAO.clar'
clarity_version = 2
epoch = 2.1

[contracts.staking-and-rewards]
path = 'contracts/staking-and-rewards.clar'
clarity_version = 2
epoch = 2.1

[contracts.susdt-token]
path = 'contracts/external/susdt-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.usda-susdt-lp-token]
path = 'contracts/external/usda-susdt-lp-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.lp-token]
path = 'contracts/lp-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.usda-token]
path = 'contracts/external/usda-token.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
