[project]
name = 'stableswap-v4'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.bitflow-sip-010]
path = 'contracts/bitflow-sip-010.clar'
clarity_version = 1
epoch = 2.05

[contracts.fee-escrow-v3]
path = 'contracts/fee-escrow-v3.clar'
clarity_version = 1
epoch = 2.05

[contracts.sip-010-trait-ft-standard]
path = 'contracts/external/sip-010-trait-ft-standard.clar'
clarity_version = 1
epoch = 2.05

[contracts.stableswap-v0-0-1]
path = 'contracts/stableswap-v0-0-1.clar'
clarity_version = 1
epoch = 2.05


[contracts.usd-lp]
path = 'contracts/usd-lp.clar'
clarity_version = 1
epoch = 2.05

[contracts.usda-token]
path = 'contracts/external/usda-token.clar'
clarity_version = 1
epoch = 2.05

[contracts.xbtc-token]
path = 'contracts/external/xbtc-token.clar'
clarity_version = 1
epoch = 2.05

[contracts.xusd-token]
path = 'contracts/external/xusd-token.clar'
clarity_version = 1
epoch = 2.05

[contracts.xusd-v2]
path = 'contracts/xusd-v2.clar'
clarity_version = 1
epoch = 2.05
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
