[project]
name = "stableswap-v4"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.fee-escrow]
path = "contracts/fee-escrow.clar"

[contracts.helper]
path = "contracts/helper.clar"

[contracts.sip-010-trait-ft-standard]
path = "contracts/external/sip-010-trait-ft-standard.clar"

[contracts.stableswap-v4]
path = "contracts/stableswap-v4.clar"

[contracts.stableswap-v5]
path = "contracts/stableswap-v5.clar"

[contracts.stableswap-v6]
path = "contracts/stableswap-v6.clar"

[contracts.usd-lp]
path = "contracts/usd-lp.clar"

[contracts.usda-token]
path = "contracts/external/usda-token.clar"

[contracts.xbtc-token]
path = "contracts/external/xbtc-token.clar"

[contracts.xusd-token]
path = "contracts/external/xusd-token.clar"

[contracts.xusd-v2]
path = "contracts/xusd-v2.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
